CREATE TABLE usuarios (
	id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL,
    email VARCHAR(80) NOT NULL,
    senha VARCHAR(80) NOT NULL,
    
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;